### ISSUE TITLE
生成的EPUB文件目录有问题

### ISSUE THREAD

**Issue by ssrkaze** [linpinger/txt2ebook#5]
**2020-05-18编译**  的版本，生产的EPUB文件要么打不开，要么打开后没有目录

**Comment by linpinger** [comment]
方便发一下文本及生成的epub文件到 linpinger_fox@163.com么

**Comment by KyriosChenn** [comment]
> 
> 
> 方便发一下文本及生成的epub文件到 [linpinger_fox@163.com](mailto:linpinger_fox@163.com)么

已发送
