### ISSUE TITLE
如何制作epub？

### ISSUE THREAD

**Issue by gulifeng8** [linpinger/txt2ebook#6]
久闻爱尔兰之狐大名，经常在各大小说下载站下载到作者是你的书，原来都是用这个工具生成的。这几年我写过n多个下载和制作txt的程序，请问怎么才能制作成upub？请原谅我做一次伸手党。

**Comment by linpinger** [comment]
菜单上有 Epub(&E)的按钮，直接就能生成，其实内容和mobi格式的一样，只是epub就是用zip压缩一下，mobi是用kindlegen转换成的

**Comment by gulifeng8** [comment]
原来如此，没好好看百科^_^

**Comment by gulifeng8** [comment]
谢谢回复
